"""new user and state models

Revision ID: 5479d2a891fc
Revises: 42d868357f2b
Create Date: 2018-08-17 11:21:07.657999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5479d2a891fc'
down_revision = '42d868357f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_timestamp'), 'state', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('address1', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('state', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'user', 'state', ['state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'website')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'state')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'company')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    op.drop_column('user', 'about_me')
    op.drop_index(op.f('ix_state_timestamp'), table_name='state')
    op.drop_table('state')
    # ### end Alembic commands ###
